-- CreateTable
CREATE TABLE `employee` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `name` VARCHAR(255) NOT NULL,
    `lastName` VARCHAR(255) NOT NULL,
    `category` ENUM('TECHNICIAN', 'ACCOUNTANT', 'MANAGER') NOT NULL DEFAULT 'TECHNICIAN',
    `salary` INTEGER NOT NULL DEFAULT 1500,
    `hiredOn` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `photoFilename` VARCHAR(255) NULL,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NULL,

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
